### ISSUE TITLE
Using the modern-nlp notebook at spacy-notebooks

### ISSUE THREAD

**Issue by bhargavvader** [skipgram/modern-nlp-in-python#1]
Hello! I've been trying to aggregate all the spaCy tutorials in the form of jupyter notebooks, when I came across your repo in the [tutorial section](https://spacy.io/docs/usage/tutorials). The notebook was very useful, and I wanted to know if it's ok if I add it to this [repo](https://github.com/explosion/spacy-notebooks).

It'll be credited (and linked) appropriately, obviously.

Thanks again for the notebook and your help!

**Comment by pwharrison** [comment]
Bhargav,

Yes, of course! Please let me know if there's anything else I can do for you.

Cheers,
Patrick


On January 10, 2017 at 10:19:31 AM, Bhargav Srinivasa (notifications@github.com) wrote:

Hello! I've been trying to aggregate all the spaCy tutorials in the form of jupyter notebooks, when I came across your repo in the tutorial section. The notebook was very useful, and I wanted to know if it's ok if I add it to this repo.

It'll be credited (and linked) appropriately, obviously.

Thanks again for the notebook and your help!

**Comment by bhargavvader** [comment]
Thanks, I've added the notebook. :)
